# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

---
title: two tauers
email: m.lisogorskyi@gmail.com
description: >-
  Set of tools to install a k3s cluster on Raspberry Pi's along with some essentials.

domain: two-tauers.github.io
url: https://two-tauers.github.io
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

# twitter_username:
github_username: two-tauers

# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

# plugins:
#   - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md # this is only for the repo
