---
name: Lint

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
