---
name: Lint & Spellcheck

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**.md"
      - "**.markdown"

jobs:

  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@v0.5.0

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
